---
title: "Multivariate Assignment 1"
author: "Tushar"
date: "2024-02-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

1. Ask an important question you want answered 

1A. Based on the industries, which country dominates in terms of the highest net worth?

1B. What age group contains the most billionaires, and in which industries are they primarily involved?

2. Answer why this question(s) is/are important to you

2A. This question is important to me because I wish to understand which industry generates the highest concentration of wealth and in which countries they are situated. By gaining the answer to this question I can find out the economic landscape of those regions. Also the knowledge of which industry generates the highest concentration can provide insights about investment decisions that are going to be made and can also help to create new business strategies.

2B. This question is important to me as I wish to understand promising industries which are thriving in that particular country. Also by understanding which industry in particular is thriving can really help in investment decisions. Also, if we find out the answer to this question then it can help both students and professionals in making informed decisions about education, training, and career paths, potentially leading to greater financial success.

3. Find and collect data (need one dependent variable and more than 3 dependent variables)

3A. Dependent - Net worth,
Independent - Country, Source, Industry 
    
3B. Dependent - Net worth                                                                                   
    Independent- Industry, Age, Source
    
    
4 Describe your data (create a data dictionary)

Ans) 
1. Variable Name - Rank,
Description - Rank of the individual based on the money they have,
Data Type - Numeric,
Unit of Measure - N/A
        
2. Variable Name - Name,
Description - Name of the person,
Data Type - Text,
Unit of Measure - N/A
        
3. Variable Name - Net worth,
Description - Total amount of money they have,
Data Type - Numeric,
Unit of Measure - Dollars
      
4. Variable Name - Age,
Description - Age of the person,
Data Type - Numeric,
Unit of Measure - Years
     
5. Variable Name - Country,
Description - Nationality of the person,
Data Type - Text,
Unit of Measure - N/A

6. Variable Name - Source,
Description - Which company or companies has made the money equaling to his net worth,
Data Type - Text,
Unit of Measure - N/A

7. Variable Name - Industry,
Description - To which industry he is working in,
Data Type - Text,
Unit of Measure - N/A,

