---
title: "Untitled"
author: "Tushar"
date: "2024-02-25"
output: html_document
---



#1) What is the mean values, covariance matrix, and Mahalanobis distances for all the variables in the dataset, and how do they differ?

library(readr)
Laptop <- read_csv("/Users/tusharkishan/Desktop/Multivariate/Assignment\ 1/Laptop_price.csv")
attach(Laptop)
str(Laptop)
Laptop$Brand <- as.factor(Laptop$Brand)
Laptop_x <- Laptop[, 2:7]
Laptop_x
Laptop_cm <- colMeans(Laptop_x)
Laptop_S <- cov(Laptop_x)
Laptop_d <- apply(Laptop_x, MARGIN = 1, function(Laptop_x)t(Laptop_x - Laptop_cm) %*% solve(Laptop_S) %*% (Laptop_x - Laptop_cm))
Laptop_cm
Laptop_S
Laptop_d

#t tests
with(data=Laptop,t.test(Processor_Speed[Brand=="Dell"],Processor_Speed[Brand=="HP"],var.equal=TRUE))
with(data=Laptop,t.test(RAM_Size[Brand=="Dell"],RAM_Size[Brand=="HP"],var.equal=TRUE))
with(data=Laptop,t.test(Storage_Capacity[Brand=="Dell"],Storage_Capacity[Brand=="HP"],var.equal=TRUE))
with(data=Laptop,t.test(Screen_Size[Brand=="Dell"],Screen_Size[Brand=="HP"],var.equal=TRUE))
with(data=Laptop,t.test(Weight[Brand=="Dell"],Weight[Brand=="HP"],var.equal=TRUE))
with(data=Laptop,t.test(Price[Brand=="Dell"],Price[Brand=="HP"],var.equal=TRUE))

#Ans) :The given R code runs numerous studies on the  dataset. Initially, it reads the dataset, which is likely to contain numerous features. It then selects all the columns from the dataset, which correspond to the brands "Dell" and "HP," respectively. Following that, the code calculates the means for the specified variables, providing information about their average values.It then computes the covariance matrix  to better understand the correlations and variability. Furthermore, the code computes Mahalanobis distances , which assess each observation's distance from the mean in multivariate space while taking covariance into account.Finally, the code uses independent t-tests to compare the means across both the laptop brands "Dell" and "HP". These t-tests seek to determine whether there are statistically significant differences in the means of these variables between the two groups, providing useful information about potential relationships with the outcome variable.The t-value indicates how different the means of the two groups are relative to the variance in the data. A larger t-value suggests a greater difference between the means.The p-value is the probability of observing such an extreme difference in means if the true difference is actually zero. A low p-value (typically below 0.05) suggests that the observed difference is unlikely to be due to random chance.The 95% confidence interval provides a range of values within which we can be 95% confident that the true difference in means lies. In this case, the interval includes zero, indicating that we cannot be confident that there is a true difference between the processor speeds of Dell and HP laptops.

#2) What are the results of Hotelling's T-squared test for all the laptop brands. What is the difference between the variances of laptops with respect to their RAM Size and Price

#Hotelling test
library(Hotelling)
new_test <- hotelling.test(Processor_Speed + RAM_Size + Storage_Capacity + Screen_Size + Weight +Price ~ Brand, data=Laptop)

cat("T2 statistic =",new_test$stat[[1]],"\n")
print(new_test)

#F tests
attach(Laptop)
var.test(RAM_Size[Brand=="Asus"],RAM_Size[Brand])
var.test(Price[Brand=="Asus"],Price[Brand])


#Ans)The Hotelling test uses a T² statistic to compare multiple means simultaneously. The T² statistic value is 4.187586, and it is used to test whether there are significant differences between the means of multiple groups.In this analysis, with a p-value of 0.6853, we do not have enough evidence to reject the null hypothesis, which would suggest that there are no significant differences between the group means.The F tests compares how much the data points vary from the mean within each group relative to the variance between the group means. A value close to 1 suggests that the variances are similar. The ratio of the variances is 0.9958122(RAM_Size) and 1.015913(Price) which means that the variances are similar.The 95% confidence interval provides a range of values within which we can be 95% confident that the true ratio of variances lies. In this case, the interval for both RAM_Size and Price includes 1, indicating that we cannot reject the null hypothesis that the variances are equal.

#4) Perform a multivariate analysis on all the laptop brands

#Anova
summary(aov(Processor_Speed ~ Brand))
summary(aov(RAM_Size ~ Brand))
summary(aov(Storage_Capacity ~ Brand))
summary(aov(Screen_Size ~ Brand))
summary(aov(Weight ~ Brand))
summary(aov(Price ~ Brand))

#Manova
summary(manova(as.matrix(Laptop[,-1])~ Brand))

#Ans)These are the results of analysis of variance (ANOVA) tests conducted to examine the differences in various laptop characteristics (Processor_Speed, RAM_Size, Storage_Capacity, Screen_Size, Weight, Price) across different laptop brands (Brand).Based on these results, none of the variables (Processor_Speed, RAM_Size, Storage_Capacity, Screen_Size, Weight, Price) show a significant difference across different laptop brands, as all p-values are greater than the typical significance level of 0.05. Finally the multivariate analysis of variance (MANOVA) assessing the effect of the "Brand" variable on several dependent variables simultaneously.In this analysis, the p-value of 0.9629 indicates that there is no significant effect of the "Brand" variable on the dependent variables.

